import { User } from '@/types';
import { UserRole } from '@/lib/permissions/roles';
import { UserDetails, UserActivity } from './users-types';

export const mockUsers: UserDetails[] = [
  {
    id: '1',
    email: 'admin@edumate.com',
    displayName: 'Super Admin',
    role: UserRole.SUPER_ADMIN,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin',
    createdAt: new Date('2024-01-01'),
    lastLoginAt: new Date(),
    status: 'active',
    major: 'Computer Science',
    bio: 'System administrator responsible for platform management and oversight.',
    groupsCount: 12,
    uploadsCount: 45,
    reportsCount: 3,
    verificationStatus: 'approved',
  },
  {
    id: '2',
    email: 'john.doe@university.edu',
    displayName: 'Dr. John Doe',
    role: UserRole.ADMIN,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=john',
    createdAt: new Date('2024-01-15'),
    lastLoginAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    status: 'active',
    major: 'Computer Science',
    bio: 'Faculty member specializing in algorithms and data structures.',
    groupsCount: 8,
    uploadsCount: 23,
    reportsCount: 7,
    verificationStatus: 'approved',
  },
  {
    id: '3',
    email: 'jane.smith@university.edu',
    displayName: 'Jane Smith',
    role: UserRole.MODERATOR,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jane',
    createdAt: new Date('2024-02-01'),
    lastLoginAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    status: 'active',
    major: 'Mathematics',
    bio: 'Graduate student and community moderator.',
    groupsCount: 6,
    uploadsCount: 12,
    reportsCount: 2,
    verificationStatus: 'approved',
  },
  {
    id: '4',
    email: 'alice.johnson@university.edu',
    displayName: 'Alice Johnson',
    role: UserRole.VIEWER,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alice',
    createdAt: new Date('2024-02-15'),
    lastLoginAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    status: 'active',
    major: 'Computer Science',
    bio: 'Undergraduate student interested in machine learning.',
    groupsCount: 4,
    uploadsCount: 8,
    reportsCount: 0,
    verificationStatus: 'pending',
  },
  {
    id: '5',
    email: 'bob.wilson@university.edu',
    displayName: 'Bob Wilson',
    role: UserRole.SUPPORT,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=bob',
    createdAt: new Date('2024-03-01'),
    lastLoginAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    status: 'inactive',
    major: 'Information Technology',
    bio: 'Technical support specialist.',
    groupsCount: 3,
    uploadsCount: 5,
    reportsCount: 1,
    verificationStatus: 'approved',
  },
  {
    id: '6',
    email: 'carol.davis@university.edu',
    displayName: 'Carol Davis',
    role: UserRole.VIEWER,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=carol',
    createdAt: new Date('2024-03-15'),
    lastLoginAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    status: 'suspended',
    major: 'Physics',
    bio: 'Physics graduate student.',
    groupsCount: 2,
    uploadsCount: 3,
    reportsCount: 0,
    verificationStatus: 'rejected',
  },
];

export const mockUserActivities: UserActivity[] = [
  {
    id: '1',
    userId: '1',
    action: 'login',
    details: 'Logged in from Chrome browser',
    timestamp: new Date(Date.now() - 5 * 60 * 1000),
    metadata: { ip: '192.168.1.100', userAgent: 'Chrome/120.0' },
  },
  {
    id: '2',
    userId: '2',
    action: 'upload_file',
    details: 'Uploaded "Algorithm Textbook.pdf"',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    metadata: { fileSize: '15MB', category: 'educational' },
  },
  {
    id: '3',
    userId: '3',
    action: 'join_group',
    details: 'Joined "Study Group - Advanced Algorithms"',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
    metadata: { groupId: 'group-123', groupName: 'Advanced Algorithms' },
  },
  {
    id: '4',
    userId: '4',
    action: 'verification_request',
    details: 'Submitted student verification documents',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
    metadata: { documentCount: 2, status: 'pending' },
  },
  {
    id: '5',
    userId: '5',
    action: 'leave_group',
    details: 'Left "General Discussion"',
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    metadata: { groupId: 'group-456', groupName: 'General Discussion' },
  },
  {
    id: '6',
    userId: '6',
    action: 'post_created',
    details: 'Created post in "Physics Study Group"',
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    metadata: { postId: 'post-789', groupId: 'group-321' },
  },
];

export const mockMajors = [
  'Computer Science',
  'Mathematics',
  'Physics',
  'Information Technology',
  'Engineering',
  'Biology',
  'Chemistry',
  'Business Administration',
  'Economics',
  'Psychology',
];
