import { Group, GroupType, GroupStatus, GroupSettings } from './groups-types';
import { UserRole } from '@/lib/permissions/roles';

export const mockGroups: Group[] = [
  {
    id: '1',
    name: 'Computer Science Study Group',
    description: 'A collaborative space for CS students to share notes, discuss algorithms, and work on projects together.',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=cs-group',
    type: 'public',
    status: 'active',
    ownerId: '2',
    createdBy: '2',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-03-15'),
    membersCount: 156,
    moderatorsCount: 3,
    messagesCount: 2847,
    mediaCount: 89,
    flaggedContentCount: 2,
    lastActivity: new Date(Date.now() - 2 * 60 * 60 * 1000),
    settings: {
      visitorPreviewEnabled: true,
      visitorCanSeeMedia: true,
      requireJoinApproval: false,
      allowMedia: true,
      maxMediaSizeMB: 50,
    },
  },
  {
    id: '2',
    name: 'Mathematics Research Team',
    description: 'Advanced mathematics research and problem-solving group for graduate students.',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=math-group',
    type: 'private',
    status: 'active',
    ownerId: '3',
    createdBy: '3',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-03-20'),
    membersCount: 42,
    moderatorsCount: 2,
    messagesCount: 1523,
    mediaCount: 34,
    lastActivity: new Date(Date.now() - 6 * 60 * 60 * 1000),
    settings: {
      visitorPreviewEnabled: false,
      visitorCanSeeMedia: false,
      requireJoinApproval: true,
      allowMedia: true,
      maxMediaSizeMB: 25,
    },
  },
  {
    id: '3',
    name: 'Physics Lab Partners',
    description: 'Experimental physics collaboration and lab work sharing.',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=physics-group',
    type: 'public',
    status: 'suspended',
    ownerId: '4',
    createdBy: '4',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-03-10'),
    membersCount: 28,
    moderatorsCount: 1,
    messagesCount: 567,
    mediaCount: 12,
    flaggedContentCount: 5,
    lastActivity: new Date(Date.now() - 24 * 60 * 60 * 1000),
    settings: {
      visitorPreviewEnabled: true,
      visitorCanSeeMedia: false,
      requireJoinApproval: false,
      allowMedia: false,
      maxMediaSizeMB: 10,
    },
  },
  {
    id: '4',
    name: 'Engineering Design Hub',
    description: 'Mechanical and electrical engineering design projects and discussions.',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=eng-group',
    type: 'public',
    status: 'active',
    ownerId: '5',
    createdBy: '5',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-03-25'),
    membersCount: 89,
    moderatorsCount: 2,
    messagesCount: 1234,
    mediaCount: 67,
    lastActivity: new Date(Date.now() - 30 * 60 * 60 * 1000),
    settings: {
      visitorPreviewEnabled: true,
      visitorCanSeeMedia: true,
      requireJoinApproval: true,
      allowMedia: true,
      maxMediaSizeMB: 100,
    },
  },
  {
    id: '5',
    name: 'Literature Discussion Circle',
    description: 'Classic and contemporary literature analysis and book club discussions.',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=lit-group',
    type: 'private',
    status: 'active',
    ownerId: '6',
    createdBy: '6',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-03-18'),
    membersCount: 34,
    moderatorsCount: 1,
    messagesCount: 892,
    mediaCount: 23,
    lastActivity: new Date(Date.now() - 4 * 60 * 60 * 1000),
    settings: {
      visitorPreviewEnabled: false,
      visitorCanSeeMedia: false,
      requireJoinApproval: true,
      allowMedia: true,
      maxMediaSizeMB: 20,
    },
  },
  {
    id: '6',
    name: 'Chemistry Study Partners',
    description: 'Organic chemistry study sessions and lab result sharing.',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=chem-group',
    type: 'public',
    status: 'archived',
    ownerId: '2',
    createdBy: '2',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-02-28'),
    membersCount: 67,
    moderatorsCount: 2,
    messagesCount: 3421,
    mediaCount: 156,
    lastActivity: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    settings: {
      visitorPreviewEnabled: true,
      visitorCanSeeMedia: true,
      requireJoinApproval: false,
      allowMedia: true,
      maxMediaSizeMB: 75,
    },
  },
  {
    id: '7',
    name: 'Business Analytics Team',
    description: 'Data analysis and business intelligence collaboration.',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=biz-group',
    type: 'private',
    status: 'active',
    ownerId: '3',
    createdBy: '3',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-28'),
    membersCount: 23,
    moderatorsCount: 1,
    messagesCount: 456,
    mediaCount: 8,
    lastActivity: new Date(Date.now() - 12 * 60 * 60 * 1000),
    settings: {
      visitorPreviewEnabled: true,
      visitorCanSeeMedia: false,
      requireJoinApproval: true,
      allowMedia: true,
      maxMediaSizeMB: 15,
    },
  },
];

export const mockGroupSpecializations = [
  'Computer Science',
  'Mathematics',
  'Physics',
  'Engineering',
  'Literature',
  'Chemistry',
  'Business',
  'Biology',
  'Psychology',
  'History',
];
