import { GroupPost, PublishRequest, GroupPostType, PostVisibility, PublishRequestStatus } from './groups-types';

export const mockGroupPosts: GroupPost[] = [
  {
    id: 'post_1',
    groupId: 'group_1',
    authorId: 'user_1',
    authorName: 'Alice Johnson',
    content: 'Welcome to our study group! This is where we\'ll share notes and discuss upcoming exams.',
    type: 'text' as GroupPostType,
    visibility: 'group_only' as PostVisibility,
    createdAt: new Date('2024-01-15T10:00:00Z'),
    updatedAt: new Date('2024-01-15T10:00:00Z'),
  },
  {
    id: 'post_2',
    groupId: 'group_1',
    authorId: 'user_2',
    authorName: 'Bob Wilson',
    content: 'Check out this helpful resource from the library: https://library.edu/physics-101',
    type: 'library_link' as GroupPostType,
    visibility: 'requested_global' as PostVisibility,
    libraryLinkUrl: 'https://library.edu/physics-101',
    createdAt: new Date('2024-01-16T14:30:00Z'),
    updatedAt: new Date('2024-01-16T14:30:00Z'),
  },
  {
    id: 'post_3',
    groupId: 'group_1',
    authorId: 'user_3',
    authorName: 'Carol Davis',
    content: 'Great discussion today! Here are my notes from the calculus lecture.',
    type: 'text' as GroupPostType,
    visibility: 'published_global' as PostVisibility,
    createdAt: new Date('2024-01-14T09:15:00Z'),
    updatedAt: new Date('2024-01-14T09:15:00Z'),
  },
  {
    id: 'post_4',
    groupId: 'group_1',
    authorId: 'user_1',
    authorName: 'Alice Johnson',
    content: 'Important announcement: Study session moved to Room 301 tomorrow.',
    type: 'text' as GroupPostType,
    visibility: 'group_only' as PostVisibility,
    createdAt: new Date('2024-01-17T16:45:00Z'),
    updatedAt: new Date('2024-01-17T16:45:00Z'),
  },
  {
    id: 'post_5',
    groupId: 'group_1',
    authorId: 'user_4',
    authorName: 'David Miller',
    content: 'Found this great video explaining quantum mechanics concepts',
    type: 'video' as GroupPostType,
    visibility: 'group_only' as PostVisibility,
    createdAt: new Date('2024-01-13T11:20:00Z'),
    updatedAt: new Date('2024-01-13T11:20:00Z'),
  }
];

export const mockPublishRequests: PublishRequest[] = [
  {
    id: 'req_1',
    postId: 'post_2',
    groupId: 'group_1',
    requestedBy: 'user_2',
    status: 'pending' as PublishRequestStatus,
    createdAt: new Date('2024-01-16T15:00:00Z'),
  },
  {
    id: 'req_2',
    postId: 'post_6',
    groupId: 'group_1',
    requestedBy: 'user_3',
    status: 'approved' as PublishRequestStatus,
    reviewedBy: 'admin_1',
    reviewedAt: new Date('2024-01-15T10:30:00Z'),
    createdAt: new Date('2024-01-14T16:45:00Z'),
  },
  {
    id: 'req_3',
    postId: 'post_7',
    groupId: 'group_1',
    requestedBy: 'user_1',
    status: 'rejected' as PublishRequestStatus,
    reviewedBy: 'admin_1',
    reviewedAt: new Date('2024-01-12T14:20:00Z'),
    createdAt: new Date('2024-01-11T09:30:00Z'),
  },
  {
    id: 'req_4',
    postId: 'post_8',
    groupId: 'group_1',
    requestedBy: 'user_4',
    status: 'pending' as PublishRequestStatus,
    createdAt: new Date('2024-01-17T17:00:00Z'),
  }
];
